
final List<Map<String,String>> photos =[
  { 'title':'Bougainvillea', 'imageUrl': 'images/bougainvillea.jpg',
    'description':'Bougainvillea is best suited to a hot, dry climate and should be watered deeply but allowed to dry out between waterings.'},
  { 'title':'Rose', 'imageUrl': 'images/rose.jpg',
    'description':'Rose is a beautiful flower with a sweet fragrance. It is a very popular flower that can be found commonly in gardens. It is my favourite flower because it is the epitome of beauty and purity. Rose signifies many emotions, like love and joy'},
  { 'title':'Daffodil', 'imageUrl': 'images/daffodil.jpg',
    'description':"Daffodils are native to northern Europe and are grown in temperate climates around the world. The daffodil's popularity has resulted in the production of many varieties in addition to the classic yellow form, the trumpet and petals may themselves be of contrasting yellow, white, pink, or orange"},
  { 'title':'Dahlia', 'imageUrl': 'images/Dahlia.jpg',
    'description':"Dahlias are perennial plants with a range of features across 42 species. Some have green herby stems, others have woody stems. The flowers are incredibly diverse, with colours including white, yellow, orange, red and purple of varying shades."},
  { 'title':'Daisy', 'imageUrl': 'images/daisy.jpg',
    'description':"The plant has leafless flower stalks and hairy bracts (leaflike structures) below the flower heads. Some varieties of the English daisy have double flowers; others may have pink or red ray flowers surrounding the bright yellow disk."},
  { 'title':'Lilly', 'imageUrl': 'images/lilly.jpg',
    'description':"Known for their trumpet-shaped blooms and sweet fragrance, lilies come in various colors and hold different meanings depending on the color.expand_more White lilies symbolize purity and innocence, while pink lilies represent affection and sympathy."},
  { 'title':'Lotus', 'imageUrl': 'images/lotus.jpg',
    'description':" Rising majestically from mud, the lotus flower symbolizes purity, enlightenment, and spiritual growth. Its beautiful blooms and long, elegant stems make it a sacred flower in many cultures."},
  { 'title':'Marigold', 'imageUrl': 'images/marigold.jpg',
    'description':" Often seen in vibrant shades of orange and yellow, marigolds represent passion, creativity, and the celebration of life. Their strong scent is believed to ward off evil spirits in some cultures."},
  { 'title':'Sunflower', 'imageUrl': 'images/sunflower.jpg',
    'description':" A symbol of joy and optimism, sunflowers boast bright yellow heads that resemble the sun.expand_more They tower over other plants and turn their faces towards the sunlight throughout the day."},
  { 'title':'Tulip', 'imageUrl': 'images/tulip.jpg',
    'description':"These vibrant spring flowers come in a wide range of colors and shapes.expand_more Tulips symbolize perfect love and new beginnings, making them popular choices for bouquets and gardens"},
  { 'title':'Arabian Jasmine', 'imageUrl': 'images/arabian_jasmine.jpg',
    'description':" With delicate white flowers and an intoxicating fragrance, Arabian jasmine embodies romance, sensuality, and purity. It's often used in perfumes and teas for its calming and uplifting properties."},
  { 'title':'Water Lily', 'imageUrl': 'images/water_lily.jpg',
    'description':"Gracefully floating on water, the waterlily symbolizes peace, tranquility, and rebirth. Its delicate beauty and ability to thrive in challenging environments inspire feelings of resilience and spiritual awakening."},
];